"""
sim.py — DEM integrator: cell-list neighbour search, force assembly, symplectic Euler.

    step(...)          advance nsub DEM steps, return mean total drag force
    settle(...)        gravity-only settling until KE is small
    ramp(...)          paper-protocol velocity ramp (0.2 m/s² up then down), ΔP(U_g)
    hold(...)          constant U_g run, ΔP(t) time series

The kernel signature is generated by Params.kernel_args(N); never build it by hand.
"""
import numpy as np
from numba import njit
from contact import pair_force, wall_forces
from drag import voidage, apply_drag


# --------------------------------------------------------------------------- kernel
@njit(cache=True, error_model="numpy")
def step(x, y, vx, vy, N, Ug, nsub, usedrag,
         dt, R, m, Iner, kn, kt, etan, etat, mu_f, g,
         W, H, NCX, NCY, dx, dy, dp, rg, mug, Vp, ap, eps_switch, eps_min,
         ncell, head, nxt, cw, ch):
    """
    Advance nsub steps. usedrag = 0/1 switches the gas coupling.
    Returns mean total drag force over the substeps (N); ΔP = F / (W d_p).
    """
    dsum = 0.0
    for _ in range(nsub):
        fx = np.zeros(N)
        fy = np.zeros(N)

        # ---- cell list (linked list per cell) ----
        for c in range(ncell):
            head[c] = -1
        for i in range(N):
            a = int(x[i] / cw)
            b = int(y[i] / ch)
            if a < 0:
                a = 0
            if a >= NCX:
                a = NCX - 1
            if b < 0:
                b = 0
            if b >= NCY:
                b = NCY - 1
            c = b * NCX + a
            nxt[i] = head[c]
            head[c] = i

        # ---- particle–particle ----
        for i in range(N):
            a = int(x[i] / cw)
            b = int(y[i] / ch)
            if a < 0:
                a = 0
            if a >= NCX:
                a = NCX - 1
            if b < 0:
                b = 0
            if b >= NCY:
                b = NCY - 1
            for da in range(-1, 2):
                for db in range(-1, 2):
                    aa = a + da
                    bb = b + db
                    if aa < 0 or aa >= NCX or bb < 0 or bb >= NCY:
                        continue
                    j = head[bb * NCX + aa]
                    while j != -1:
                        if j > i:
                            Fx, Fy, hit = pair_force(x[j] - x[i], y[j] - y[i],
                                                     vx[j] - vx[i], vy[j] - vy[i],
                                                     R, kn, etan, etat, mu_f)
                            if hit:
                                fx[i] += Fx
                                fy[i] += Fy
                                fx[j] -= Fx
                                fy[j] -= Fy
                        j = nxt[j]

        # ---- walls ----
        for i in range(N):
            Fx, Fy = wall_forces(x[i], y[i], vx[i], vy[i], R, W, kn, etan, etat, mu_f)
            fx[i] += Fx
            fy[i] += Fy

        # ---- gas drag (one-way coupling, recomputed every step) ----
        if usedrag == 1:
            eps = voidage(x, y, N, NCX, NCY, dx, dy, Vp, dp, eps_min)
            dsum += apply_drag(x, y, vy, fy, N, Ug, eps, NCX, NCY, dx, dy,
                               dp, rg, mug, Vp, eps_switch)

        # ---- symplectic Euler ----
        for i in range(N):
            vx[i] += dt * fx[i] / m
            vy[i] += dt * (fy[i] / m - g)
            x[i] += dt * vx[i]
            y[i] += dt * vy[i]
            if y[i] > H - R:           # hard ceiling (paper uses a pressure outlet)
                y[i] = H - R
                if vy[i] > 0.0:
                    vy[i] = 0.0
    return dsum / nsub


# --------------------------------------------------------------------------- drivers
def kinetic_energy(vx, vy, m):
    return 0.5 * m * float(np.sum(vx * vx + vy * vy))


def settle(state, p, args, t_settle=0.4, chunk=20000, ke_tol=1e-6, verbose=True):
    """Gravity-only settling for t_settle seconds (or until KE < ke_tol). Modifies state in place."""
    x, y, vx, vy = state
    N = x.size
    nchunks = max(1, int(t_settle / (chunk * p.dt)))
    for k in range(nchunks):
        step(x, y, vx, vy, N, 0.0, chunk, 0, *args)
        ke = kinetic_energy(vx, vy, p.m)
        if verbose:
            print(f"  settle t={(k+1)*chunk*p.dt:.3f} s  h={y.max():.4f} m  KE={ke:.3e} J")
        if ke < ke_tol and k > 2:
            break
    return y.max()


def ramp(state, p, args, verbose=True):
    """
    Paper protocol: U_g from 0 → Ug_max at ramp_rate, then back to 0.
    Samples ΔP at sample_hz. Returns dict with t, Ug, dP, branch (+1 up / −1 down), h.
    """
    x, y, vx, vy = state
    N = x.size
    nsub = max(1, int(round(1.0 / (p.sample_hz * p.dt))))     # DEM steps per sample
    dt_s = nsub * p.dt
    t_up = p.Ug_max / p.ramp_rate
    n_up = int(round(t_up / dt_s))
    t, Ugs, dPs, br, hs = [], [], [], [], []
    tt = 0.0
    for k in range(2 * n_up):
        if k < n_up:
            Ug = p.ramp_rate * tt
            b = 1
        else:
            Ug = max(0.0, p.Ug_max - p.ramp_rate * (tt - t_up))
            b = -1
        F = step(x, y, vx, vy, N, Ug, nsub, 1, *args)
        tt += dt_s
        t.append(tt)
        Ugs.append(Ug)
        dPs.append(F / (p.W * p.dp))
        br.append(b)
        hs.append(y.max())
        if verbose and k % max(1, (2 * n_up) // 20) == 0:
            print(f"  t={tt:6.2f} s  Ug={Ug:5.3f}  dP={dPs[-1]:7.1f} Pa  h={hs[-1]*1e3:6.1f} mm")
    return dict(t=np.array(t), Ug=np.array(Ugs), dP=np.array(dPs),
                branch=np.array(br), h=np.array(hs))


def hold(state, p, args, Ug, t_hold, verbose=True):
    """Constant-U_g run; returns ΔP(t) sampled at sample_hz (for PSD / RMS analysis)."""
    x, y, vx, vy = state
    N = x.size
    nsub = max(1, int(round(1.0 / (p.sample_hz * p.dt))))
    n = int(round(t_hold * p.sample_hz))
    t = np.arange(1, n + 1) / p.sample_hz
    dP = np.empty(n)
    for k in range(n):
        F = step(x, y, vx, vy, N, Ug, nsub, 1, *args)
        dP[k] = F / (p.W * p.dp)
        if verbose and k % max(1, n // 10) == 0:
            print(f"  t={t[k]:5.2f} s  dP={dP[k]:7.1f} Pa  h={y.max()*1e3:6.1f} mm")
    return t, dP
